spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product1?enabledTLSProtocols=TLSv1.2
    username: root
    password: Ravi123$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: create.sql
              create-source: metadata


