db_mysql:
  environment:
    MYSQL_DATABASE: 'db_spring'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: 'Ravi123$'
    MYSQL_ROOT_PASSWORD: 'Ravi123$'
    MYSQL_TCP_PORT: 3306
  ports:
    - 3306:3306
  expose:
    - '3306'
  volumes:
    - ./db_mysql:/docker-entrypoint-initdb.d/
    - db_mysql:/var/lib/mysql
  networks:
    - networ