version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Maven Clean Install
          command: mvn clean install