version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Maven Clean Install
          command: mvn clean install